jobs:
- deployment: deploymentJob1
  environment: testEnvironmentCheck
  pool: testAgent1
  strategy:
   runOnce:
    deploy:
     steps:
     - script: echo Hello, world!
       displayName: 'Run a one-line script'